name: display_screen_demo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.0
  carousel_slider: ^4.1.1
  dio: ^5.4.3+1
  get: ^4.6.1
  get_storage: ^2.0.3
  sqflite: ^2.3.3+1
  dartz: ^0.10.1
  video_player: ^2.9.1
  workmanager: ^0.5.2
  cupertino_icons: ^1.0.6
  youtube_player_flutter: ^9.0.2
  shimmer: ^3.0.0
  flutter_html_video: ^3.0.0-beta.2
  animated_text_kit: ^4.2.2
  flutter_html: ^3.0.0-beta.2
  install_plugin: ^2.1.0
  flutter_app_update: ^3.1.0
  permission_handler: ^11.3.1




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
   # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
